REM	-----------------------------------------------
REM	
REM	ORTEC Job File : Begin_Det2_Single_Cal.Job
REM   
REM	Description : Calibration of Detector 2 for single livestock geometry
REM 
REM	Application Software : A65-BW V7.01
REM
REM	Job Version 1.1
REM
REM	Date : 25 Dec. 2014
REM
REM     -------------------------------------------------------------
REM	
REM	Description :
REM
REM	Detector 2 Calibration for single livestock
REM
REM	5 nuclides ( default ); i.e. n = 5 
REM
REM	DET2_ROI5.ROI is using for ROI report ( default )
REM
REM	Calibration time per nuclide is 300 seconds default ( 5 secs for testing )
REM
REM	Spectrum stores at MCA memory after counting
REM
REM	Saved spectrum C:\LCMS\Spectra\DET2_Single_Cal_n.Chn; where n is no. of nuclide
REM
REM	ROI report ( ASCII ) will be generated after elapsed of measuring time
REM
REM	ROI report saved as : C:\LCMS\Data\DET2_Single_Cal_n.Dat; where n is no. of nuclide.
REM
REM	--------------------------------------------------------------


REM Close all buffers if any

CLOSEBUFFERS


REM	------------------------------------------------------
REM 	Set ZOOM -1 for minimize Maestro window after debug
REM 	------------------------------------------------------

REM	----------------------------------------------------------
REM	Stop, clear MCA and preset live time for detector 2
REM	----------------------------------------------------------


REM ----------------------------------------------------------
SET_DETECTOR 2
STOP
CLEAR
SET_PRESET_CLEAR

REM ** modify below command for different ROI file of Det2
RECALL_ROI "C:\LCMS\ROI\DET2_ROI5.ROI"

REM ** modify below command for different counting time in second per nuclide
SET_PRESET_LIVE 5


	REM Modify loop value for total number of nuclides
	Loop 5

	REM ***************** Start of looping ******************

	DESCRIBE_SAMPLE "Detector 2 Nuclide $(Loop1)"
	ASK_CONFIRM "Place Calibration Standard < $(Loop1) > in Position, then press OK"

	CLEAR
	START

	WAIT 2
	WAIT

	REM Save calibration spectrum of current nuclide
	REM $(Loop1) has value of 1, 2, 3, 4 and 5 for "Loop 5" command

	REM ASK_CONFIRM "Pause for saving detector 2 spectrum"	

	SAVE "C:\LCMS\SPECTRA\DET2_Single_Cal_$(Loop1).Chn"
	WAIT
	REPORT "C:\LCMS\Data\DET2_Single_Cal_$(Loop1).Dat"
	WAIT

	End_Loop

ASK_CONFIRM "Calibration Done O.K. !"


REM quit Maestro and return to calling program 
REM QUIT

REM * * * * Job file end * * * *

