//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMS.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangZn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangZn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCMS.Lang.LangZn", typeof(LangZn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇戶口類型.
        /// </summary>
        internal static string accountType {
            get {
                return ResourceManager.GetString("accountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入警告數值.
        /// </summary>
        internal static string alarmLevel {
            get {
                return ResourceManager.GetString("alarmLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入branch of peak ration.
        /// </summary>
        internal static string bop {
            get {
                return ResourceManager.GetString("bop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋 inpout32.dll.
        /// </summary>
        internal static string checkIO {
            get {
                return ResourceManager.GetString("checkIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入code 或 description.
        /// </summary>
        internal static string codeDescription {
            get {
                return ResourceManager.GetString("codeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code 不能重覆.
        /// </summary>
        internal static string codeDuplicateError {
            get {
                return ResourceManager.GetString("codeDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定進行Background?.
        /// </summary>
        internal static string confirmBkTxt {
            get {
                return ResourceManager.GetString("confirmBkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定執行Calibration?.
        /// </summary>
        internal static string confirmCalibrationTxt {
            get {
                return ResourceManager.GetString("confirmCalibrationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 決定離開?.
        /// </summary>
        internal static string confirmExit {
            get {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確定執行Measurement?.
        /// </summary>
        internal static string confirmMeasureTxt {
            get {
                return ResourceManager.GetString("confirmMeasureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接駁Detector 1中....
        /// </summary>
        internal static string connectDetector1 {
            get {
                return ResourceManager.GetString("connectDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接駁Detector 2中....
        /// </summary>
        internal static string connectDetector2 {
            get {
                return ResourceManager.GetString("connectDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算率:.
        /// </summary>
        internal static string countRate {
            get {
                return ResourceManager.GetString("countRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 現行 Background 數值.
        /// </summary>
        internal static string currBgStatusPanel {
            get {
                return ResourceManager.GetString("currBgStatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下載.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入英文名.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入英文或中文名.
        /// </summary>
        internal static string engChi {
            get {
                return ResourceManager.GetString("engChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到mca32.exe.
        /// </summary>
        internal static string exeNotFound {
            get {
                return ResourceManager.GetString("exeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連接Detector 1失敗.
        /// </summary>
        internal static string failConnectDetector1 {
            get {
                return ResourceManager.GetString("failConnectDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連接Detector 2失敗.
        /// </summary>
        internal static string failConnectDetector2 {
            get {
                return ResourceManager.GetString("failConnectDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋上次的工作中....
        /// </summary>
        internal static string findPreviousJob {
            get {
                return ResourceManager.GetString("findPreviousJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取回Bgd Data.
        /// </summary>
        internal static string getBKPrevDataBtn {
            get {
                return ResourceManager.GetString("getBKPrevDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入 half-life 數值及選擇單位.
        /// </summary>
        internal static string halfLife {
            get {
                return ResourceManager.GetString("halfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 讀取 Basic.xml.
        /// </summary>
        internal static string loadBasicXML {
            get {
                return ResourceManager.GetString("loadBasicXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入為:.
        /// </summary>
        internal static string loginAsTxt {
            get {
                return ResourceManager.GetString("loginAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        internal static string loginBtnTxt {
            get {
                return ResourceManager.GetString("loginBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string loginOutTxt {
            get {
                return ResourceManager.GetString("loginOutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登出.
        /// </summary>
        internal static string logoutText {
            get {
                return ResourceManager.GetString("logoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入Major Peak Energy.
        /// </summary>
        internal static string mpe {
            get {
                return ResourceManager.GetString("mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新執行Background數值.
        /// </summary>
        internal static string newBkStatus {
            get {
                return ResourceManager.GetString("newBkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        internal static string noBtnTxt {
            get {
                return ResourceManager.GetString("noBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string noticeMsg {
            get {
                return ResourceManager.GetString("noticeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 開啟報告.
        /// </summary>
        internal static string openBtnTxt {
            get {
                return ResourceManager.GetString("openBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 來源地不能重覆.
        /// </summary>
        internal static string originDuplicate {
            get {
                return ResourceManager.GetString("originDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇分類.
        /// </summary>
        internal static string parameterType {
            get {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入密碼及最少8位字元.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 計算時間:.
        /// </summary>
        internal static string preCountLabel {
            get {
                return ResourceManager.GetString("preCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 執行日期:.
        /// </summary>
        internal static string preDateLabel {
            get {
                return ResourceManager.GetString("preDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地點:.
        /// </summary>
        internal static string preLocationLabel {
            get {
                return ResourceManager.GetString("preLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total 總計算率:.
        /// </summary>
        internal static string preRateLabel {
            get {
                return ResourceManager.GetString("preRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 列印報告.
        /// </summary>
        internal static string printBtnTxt {
            get {
                return ResourceManager.GetString("printBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不能選擇空白Profile.
        /// </summary>
        internal static string profileError {
            get {
                return ResourceManager.GetString("profileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile 檔案失效, 請刪除及重新計算.
        /// </summary>
        internal static string profileFileError {
            get {
                return ResourceManager.GetString("profileFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到Profile 檔案.
        /// </summary>
        internal static string profileNotFound {
            get {
                return ResourceManager.GetString("profileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 執行.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 執行Background計算.
        /// </summary>
        internal static string runBk {
            get {
                return ResourceManager.GetString("runBk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm up進行中....
        /// </summary>
        internal static string runWarmUp {
            get {
                return ResourceManager.GetString("runWarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已儲存.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇script file.
        /// </summary>
        internal static string scriptFile {
            get {
                return ResourceManager.GetString("scriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜尋.
        /// </summary>
        internal static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 選擇Profile 成功.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請選擇執行地點.
        /// </summary>
        internal static string selectLocation {
            get {
                return ResourceManager.GetString("selectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        internal static string settingBtnTxt {
            get {
                return ResourceManager.GetString("settingBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 狀態:.
        /// </summary>
        internal static string statusTxt {
            get {
                return ResourceManager.GetString("statusTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連接Detector 1成功.
        /// </summary>
        internal static string successDetector1 {
            get {
                return ResourceManager.GetString("successDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 連接Detector 2成功.
        /// </summary>
        internal static string successDetector2 {
            get {
                return ResourceManager.GetString("successDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已執行3次仍未能取回資料, 重試?.
        /// </summary>
        internal static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新Background數值.
        /// </summary>
        internal static string updBk {
            get {
                return ResourceManager.GetString("updBk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請輸入用戶名稱.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認開始Warm Up?.
        /// </summary>
        internal static string WarmUpTxt {
            get {
                return ResourceManager.GetString("WarmUpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        internal static string yesBtnTxt {
            get {
                return ResourceManager.GetString("yesBtnTxt", resourceCulture);
            }
        }
    }
}
