//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCMS.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LCMS.Lang.LangEn", typeof(LangEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select account type.
        /// </summary>
        internal static string accountType {
            get {
                return ResourceManager.GetString("accountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter alarm level.
        /// </summary>
        internal static string alarmLevel {
            get {
                return ResourceManager.GetString("alarmLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter branch of peak ration.
        /// </summary>
        internal static string bop {
            get {
                return ResourceManager.GetString("bop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking inpout32.dll.
        /// </summary>
        internal static string checkIO {
            get {
                return ResourceManager.GetString("checkIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter either code or description.
        /// </summary>
        internal static string codeDescription {
            get {
                return ResourceManager.GetString("codeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code cannot duplicate.
        /// </summary>
        internal static string codeDuplicateError {
            get {
                return ResourceManager.GetString("codeDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to run background?.
        /// </summary>
        internal static string confirmBkTxt {
            get {
                return ResourceManager.GetString("confirmBkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to run Calibration?.
        /// </summary>
        internal static string confirmCalibrationTxt {
            get {
                return ResourceManager.GetString("confirmCalibrationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Exit?.
        /// </summary>
        internal static string confirmExit {
            get {
                return ResourceManager.GetString("confirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to Run Measurement?.
        /// </summary>
        internal static string confirmMeasureTxt {
            get {
                return ResourceManager.GetString("confirmMeasureTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Detector 1....
        /// </summary>
        internal static string connectDetector1 {
            get {
                return ResourceManager.GetString("connectDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to Detector 2....
        /// </summary>
        internal static string connectDetector2 {
            get {
                return ResourceManager.GetString("connectDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Rate:.
        /// </summary>
        internal static string countRate {
            get {
                return ResourceManager.GetString("countRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Background Status.
        /// </summary>
        internal static string currBgStatusPanel {
            get {
                return ResourceManager.GetString("currBgStatusPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter English Name.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Eng or Chinese Name.
        /// </summary>
        internal static string engChi {
            get {
                return ResourceManager.GetString("engChi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find mca32.exe.
        /// </summary>
        internal static string exeNotFound {
            get {
                return ResourceManager.GetString("exeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to connect to Detector 1.
        /// </summary>
        internal static string failConnectDetector1 {
            get {
                return ResourceManager.GetString("failConnectDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to connect to Detector 2.
        /// </summary>
        internal static string failConnectDetector2 {
            get {
                return ResourceManager.GetString("failConnectDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding previous job....
        /// </summary>
        internal static string findPreviousJob {
            get {
                return ResourceManager.GetString("findPreviousJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Previous Bgd Data?.
        /// </summary>
        internal static string getBKPrevDataBtn {
            get {
                return ResourceManager.GetString("getBKPrevDataBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter half-life value and select unit.
        /// </summary>
        internal static string halfLife {
            get {
                return ResourceManager.GetString("halfLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login As:.
        /// </summary>
        internal static string loginAsTxt {
            get {
                return ResourceManager.GetString("loginAsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginBtnTxt {
            get {
                return ResourceManager.GetString("loginBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string loginOutTxt {
            get {
                return ResourceManager.GetString("loginOutTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutText {
            get {
                return ResourceManager.GetString("logoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Major Peak Energy.
        /// </summary>
        internal static string mpe {
            get {
                return ResourceManager.GetString("mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Run Background Status.
        /// </summary>
        internal static string newBkStatus {
            get {
                return ResourceManager.GetString("newBkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string noBtnTxt {
            get {
                return ResourceManager.GetString("noBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Message.
        /// </summary>
        internal static string noticeMsg {
            get {
                return ResourceManager.GetString("noticeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Report.
        /// </summary>
        internal static string openBtnTxt {
            get {
                return ResourceManager.GetString("openBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin cannot duplicate.
        /// </summary>
        internal static string originDuplicate {
            get {
                return ResourceManager.GetString("originDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Parameter Type.
        /// </summary>
        internal static string parameterType {
            get {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password and password at least 8 digit.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting Time:.
        /// </summary>
        internal static string preCountLabel {
            get {
                return ResourceManager.GetString("preCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Acquired:.
        /// </summary>
        internal static string preDateLabel {
            get {
                return ResourceManager.GetString("preDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Location:.
        /// </summary>
        internal static string preLocationLabel {
            get {
                return ResourceManager.GetString("preLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Count Rate:.
        /// </summary>
        internal static string preRateLabel {
            get {
                return ResourceManager.GetString("preRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        internal static string printBtnTxt {
            get {
                return ResourceManager.GetString("printBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot select empty profile.
        /// </summary>
        internal static string profileError {
            get {
                return ResourceManager.GetString("profileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find profile file, please delete and run again.
        /// </summary>
        internal static string profileFileError {
            get {
                return ResourceManager.GetString("profileFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile file can&apos;t find.
        /// </summary>
        internal static string profileNotFound {
            get {
                return ResourceManager.GetString("profileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Background.
        /// </summary>
        internal static string runBk {
            get {
                return ResourceManager.GetString("runBk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Warm up....
        /// </summary>
        internal static string runWarmUp {
            get {
                return ResourceManager.GetString("runWarmUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select script file.
        /// </summary>
        internal static string scriptFile {
            get {
                return ResourceManager.GetString("scriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Profile Successful.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select operation location.
        /// </summary>
        internal static string selectLocation {
            get {
                return ResourceManager.GetString("selectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string settingBtnTxt {
            get {
                return ResourceManager.GetString("settingBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        internal static string statusTxt {
            get {
                return ResourceManager.GetString("statusTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Detector 1 Successful.
        /// </summary>
        internal static string successDetector1 {
            get {
                return ResourceManager.GetString("successDetector1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Detector 2 Successful.
        /// </summary>
        internal static string successDetector2 {
            get {
                return ResourceManager.GetString("successDetector2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried 3 times, try again?.
        /// </summary>
        internal static string tryAgain {
            get {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Background Status.
        /// </summary>
        internal static string updBk {
            get {
                return ResourceManager.GetString("updBk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter User Name.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to start warm up process?.
        /// </summary>
        internal static string WarmUpTxt {
            get {
                return ResourceManager.GetString("WarmUpTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yesBtnTxt {
            get {
                return ResourceManager.GetString("yesBtnTxt", resourceCulture);
            }
        }
    }
}
